name: Koi Chi Healing
favicon: null
layout_spectrum: 0.38902
typography_spectrum: 0.89106
title: 'Jocelyn Lee | Koi Chi Healing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5abfdb'
    - '#ffcaa9'
    - '#fffdff'
    - '#616e67'
    - '#23383b'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
